C------------------------------------------------------------------------
C
C     This routine was automatically generated by SPACK.
C
C------------------------------------------------------------------------
 
      subroutine dimensions_racm2                        (
     $    Ns, Nr, Nr_photolysis)
 
C------------------------------------------------------------------------
C
      integer Ns, Nr, Nr_photolysis
 
      Ns =   117
      Nr =   389
      Nr_photolysis =    34
 
      RETURN
      END
 
